name: daily-automatic-update
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

env:
  USERNAME: ${{ secrets.USERNAME }}
  GH__TOKEN: ${{ secrets.GH__TOKEN }}
  NAME: ${{ secrets.NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  NUGET__TOKEN: ${{ secrets.NUGET__TOKEN }}
  GIT__TOKEN: ${{ secrets.GIT__TOKEN }}
  
jobs:

  daily-automatic-update:
    runs-on: windows-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Setting up build version
        run: |
          version=$(($GITHUB_RUN_NUMBER))
          echo "BUILD_VERSION=3.0.$version" >> ${GITHUB_ENV}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Run
        run: dotnet run --project src/Soenneker.Git.Runners.Windows.csproj --no-restore --verbosity normal --framework net9.0 --configuration Release
