name: daily-automatic-update
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

env:
  USERNAME: ${{ secrets.USERNAME }}
  GH__TOKEN: ${{ secrets.GH__TOKEN }}
  NAME: ${{ secrets.NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  NUGET__TOKEN: ${{ secrets.NUGET__TOKEN }}
  GIT__TOKEN: ${{ secrets.GIT__TOKEN }}
  
jobs:

  daily-automatic-update:
    runs-on: windows-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Setting up build version
        shell: pwsh
        run: |
          $version = "3.0.$env:GITHUB_RUN_NUMBER"
          echo "BUILD_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies with retry
        shell: pwsh
        run: |
          $retries = 5
          $baseWaitTime = 15
          $exponent = 2

          for ($i = 1; $i -le $retries; $i++) {
            if (dotnet restore) {
              break
            }
            if ($i -lt $retries) {
              $waitTime = [math]::Pow($baseWaitTime * $exponent, $i - 1)
              Write-Host "dotnet restore failed, retrying in $waitTime seconds..."
              Start-Sleep -Seconds $waitTime
            } else {
              Write-Host "dotnet restore failed after $retries retries."
              exit 1
            }
          }

      - name: Build for all frameworks
        run: dotnet build --configuration Release --no-restore

      - name: Run
        run: dotnet run --project src/Soenneker.Git.Runners.Windows.csproj --no-restore --verbosity normal --framework net9.0 --configuration Release
